name: Preview Deploy Story book to GitHub Pages

on:
  pull_request:
    types: [closed, opened]

jobs:
  preview-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3


  # GitHub PagesにデプロイしたStorybookをたたむ
  clean-up:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
